cloud:
    aws:
        credentials:
            access-key: AKIAZXD2AXE5RPNKJNXO
            secret-key: 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
        region:
            static: ap-northeast-2
        s3:
            bucket: sgfp
        stack:
            auto: false
eureka:
    client:
        disable-delta: true
        fetch-registry: true
        register-with-eureka: true
        registry-fetch-interval-seconds: 10
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true
logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8001
spring:
    application:
        name: user-server
    data:
        neo4j:
            database: neo4j
    neo4j:
        authentication:
            password: 1234
            username: neo4j
        uri: bolt://localhost:7687
